<html> 
 
<head> 
  <title>Publisher Application</title> 
</head> 
 
<body style="margin: 0; padding: 0"> 
 
<table width="728" 
           cellspacing="0" 
           cellpadding="0"
           style="padding: 0; margin: 0; border-collapse: collapse"> 
<tr style="padding: 0; margin: 0"> 
<td width="728" 
       colspan="2" 
       style="padding: 0; margin: 0"><img 
          src="logo.gif" 
          style="padding: 0; margin"></td> 
</tr> 
<tr style="padding: 0; margin: 0"> 
<td width="728" 
       colspan="2" 
       style="padding: 0; margin: 0"><div 
         style="padding: 5; 
                    margin: 0; 
                    text-align: center;
                    font-size: small; 
                    background-color: #99CCCC"> 
       <h2>Publisher Application<h2>
</div></td> 
</tr> 
<tr> 
    <td rowspan="2" 
           width="240"
           valign="top"> 
       <div style="height: 200px; padding: 20px; border-right: 3px dashed; margin-top: 20px; margin-right: 20px"> 
          <a href="list-news-items">List News Items</a><br/> 
          <a href="create-news-item">Create News Item</a><br/> 
          <a href="logout">Logout</a> <br/> 
       </div> 
    </td> 
    <td width="488" valign="top"> 
         <div style="margin-top: 20px; margin-bottom: 1 px">